default: &default
  adapter: postgresql
  prepared_statements: true
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: paperkite_development

test:
  <<: *default
  database: paperkite_test<%= ENV['TEST_ENV_NUMBER'] %>